install:
	javac *.java

run:
	javac *.java
	java Window
	rm *.class

clean:
	rm *.class
	rm *.java~
	
cleanWindows:
	del /f *.class
	del /f *.java~

runWindows:
	javac *.java
	java Window
	del /f *.class